### ISSUE TITLE
HTTPS Certificate Mismatch

### ISSUE THREAD

**Issue by tadman** [petdance/bobby-tables#84]
It seems that https://bobby-tables.com/ has a rejected certificate because that certificate is actually for beyondgrep.com.

Would be nice to have a TLS link that can be shared.

**Comment by petdance** [comment]
Thanks for the report.  How do you mean it has a "rejected certificate"?  Rejected how and where?

**Comment by tadman** [comment]
The certificate that comes up is actually for the wrong domain, it's for beyondgrep.com, so when you visit bobby-tables.com any browser will show a warning that it's invalid.

You can test this with a variety of [diagnostic tools](https://www.digicert.com/help/), including `curl` which shows:

```
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html
```

**Comment by petdance** [comment]
It's funny, I don't think I ever intended bobby-tables.com to have a certificate.  I'll look into this.  Thanks.

**Comment by dz-at-tc** [comment]
I think this issue has been resolved since the last update above.

curl now reports:

* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=bobby-tables.com
*  start date: Aug 24 00:36:34 2021 GMT
*  expire date: Nov 22 00:36:33 2021 GMT
*  subjectAltName: host "bobby-tables.com" matched cert's "bobby-tables.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.

Likewise, chrome says the certificate is valid and issued to bobby-tables.com

Thus probably ok to close this issue, mais non?

**Comment by petdance** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=bobby-tables.com is happy.
